@startuml
package BitPacker {

interface BitPacker {
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
    int[] getCompressedData()
}

class BitPackerOverlap implements BitPacker {
    int k
    int originalLength
    int[] compressed
    BitPackerOverlap()
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
    void maxK(int[] tab)
    int[] getCompressedData()
}

class BitPackerNoOverlap implements BitPacker {
    int k
    int nPerInt
    int originalLength
    int[] compressed
    BitPackerNoOverlap()
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
    void maxK(int[] tab)
    int[] getCompressedData()
}

class BitPackerOverflow implements BitPacker {
    int kNormal
    int kOverflowIndex
    int payloadWidth
    int packedK
    int originalLength
    int[] compressedOverflow
    BitPackerOverflow(BitPacker internalPacker)
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
    int getKForValue(int val)
    int[] getCompressedData()
}

class BitPackerFactory {
    BitPacker create(CompressionType type)
}

class BenchmarkRunner {
    int ARRAY_SIZE
    int WARMUP_RUNS
    int TIMING_RUNS
    void main(String[] args)
    void runAllTests(int[] data)
    void runTest(BitPackerFactory.CompressionType type, int[] data)
    int[] generateRandomData(int size, int maxValue)
    int[] generateOverflowData(int size, int normalMax, int outlierMax, double outlierChance)
}

class Main {
    void main(String[] args)
}

BitPackerOverflow -- "1" BitPacker

}
@enduml