@startuml
package BitPacker {

interface BitPacker {
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
}

class BitPackerOverlap implements BitPacker {
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
}

class BitPackerNoOverlap implements BitPacker {
    int k
    int nPerInt
    int originalLength
    int[] compressed
    void compress(int[] input)
    void decompress(int[] output)
    int get(int i)
    void maxK(int[] tab)
}

class BitPackerFactory {
}
}
@enduml